function GetZoneHasAuctionHouse(ZoneID)
	return MAP_ZONES[ZoneID]["HasAuctionHouse"]
end

MAP_ZONES =
{
	[1] = 	{id="Phanauet Channel",					HasAuctionHouse=false},
	[2] = 	{id="Carpenters' Landing",				HasAuctionHouse=false},
	[3] = 	{id="Manaclipper",						HasAuctionHouse=false},
	[4] = 	{id="Bibiki Bay",						HasAuctionHouse=false},
	[5] = 	{id="Uleguerand Range",					HasAuctionHouse=false},
	[6] = 	{id="Bearclaw Pinnacle",				HasAuctionHouse=false},
	[7] = 	{id="Attohwa Chasm",					HasAuctionHouse=false},
	[8] = 	{id="Boneyard Gully",					HasAuctionHouse=false},
	[9] = 	{id="Pso'Xja",							HasAuctionHouse=false},
	[10] = 	{id="The Shrouded Maw",					HasAuctionHouse=false},
	[11] = 	{id="Oldton Movalpolos",				HasAuctionHouse=false},
	[12] = 	{id="Newton Movalpolos",				HasAuctionHouse=false},
	[13] = 	{id="Mine Shaft #2716",					HasAuctionHouse=false},
	[14] = 	{id="Hall of Transference",				HasAuctionHouse=false},
	[15] = 	{id="Abyssea - Konschtat",				HasAuctionHouse=false},
	[16] = 	{id="Promyvion - Holla",				HasAuctionHouse=false},
	[17] = 	{id="Spire of Holla",					HasAuctionHouse=false},
	[18] = 	{id="Promyvion - Dem",					HasAuctionHouse=false},
	[19] = 	{id="Spire of Dem",						HasAuctionHouse=false},
	[20] = 	{id="Promyvion - Mea",					HasAuctionHouse=false},
	[21] = 	{id="Spire of Mea",						HasAuctionHouse=false},
	[22] = 	{id="Promyvion - Vahzl",				HasAuctionHouse=false},
	[23] = 	{id="Spire of Vahzl",					HasAuctionHouse=false},
	[24] = 	{id="Lufaise Meadows",					HasAuctionHouse=false},
	[25] = 	{id="Misareaux Coast",					HasAuctionHouse=false},
	[26] = 	{id="Tavnazian Safehold",				HasAuctionHouse=true},
	[27] = 	{id="Phomiuna Aqueducts",				HasAuctionHouse=false},
	[28] = 	{id="Sacrarium",						HasAuctionHouse=false},
	[29] = 	{id="Riverne - Site #B01",				HasAuctionHouse=false},
	[30] = 	{id="Riverne - Site #A01",				HasAuctionHouse=false},
	[31] = 	{id="Monarch Linn",						HasAuctionHouse=false},
	[32] = 	{id="Sealion's Den",					HasAuctionHouse=false},
	[33] = 	{id="Al'Taieu",							HasAuctionHouse=false},
	[34] = 	{id="Grand Palace of Hu'Xzoi",			HasAuctionHouse=false},
	[35] = 	{id="The Garden of Ru'Hmet",			HasAuctionHouse=false},
	[36] = 	{id="Empyreal Paradox",					HasAuctionHouse=false},
	[37] = 	{id="Temenos",							HasAuctionHouse=false},
	[38] = 	{id="Apollyon",							HasAuctionHouse=false},
	[39] = 	{id="Dynamis - Valkurm",				HasAuctionHouse=false},
	[40] = 	{id="Dynamis - Buburimu",				HasAuctionHouse=false},
	[41] = 	{id="Dynamis - Qufim",					HasAuctionHouse=false},
	[42] = 	{id="Dynamis - Tavnazia",				HasAuctionHouse=false},
	[43] = 	{id="Diorama Abdhaljs-Ghelsba",			HasAuctionHouse=false},
	[44] = 	{id="Abdhaljs Isle-Purgonorgo",			HasAuctionHouse=false},
	[45] = 	{id="Abyssea - Tahrongi",				HasAuctionHouse=false},
	[46] = 	{id="Open sea route to Al Zahbi",		HasAuctionHouse=false},
	[47] = 	{id="Open sea route to Mhaura",			HasAuctionHouse=false},
	[48] = 	{id="Al Zahbi",							HasAuctionHouse=true},
	[50] = 	{id="Aht Urhgan Whitegate",				HasAuctionHouse=true},
	[51] = 	{id="Wajaom Woodlands",					HasAuctionHouse=false},
	[52] = 	{id="Bhaflau Thickets",					HasAuctionHouse=false},
	[53] = 	{id="Nashmau",							HasAuctionHouse=true},
	[54] = 	{id="Arrapago Reef",					HasAuctionHouse=false},
	[55] = 	{id="Ilrusi Atoll",						HasAuctionHouse=false},
	[56] = 	{id="Periqia",							HasAuctionHouse=false},
	[57] = 	{id="Talacca Cove",						HasAuctionHouse=false},
	[58] = 	{id="Silver Sea route to Nashmau",		HasAuctionHouse=false},
	[59] = 	{id="Silver Sea route to Al Zahbi",		HasAuctionHouse=false},
	[60] = 	{id="The Ashu Talif",					HasAuctionHouse=false},
	[61] = 	{id="Mount Zhayolm",					HasAuctionHouse=false},
	[62] = 	{id="Halvung",							HasAuctionHouse=false},
	[63] = 	{id="Lebros Cavern",					HasAuctionHouse=false},
	[64] = 	{id="Navukgo Execution Chamber",		HasAuctionHouse=false},
	[65] = 	{id="Mamook",							HasAuctionHouse=false},
	[66] = 	{id="Mamool Ja Training Grounds",		HasAuctionHouse=false},
	[67] = 	{id="Jade Sepulcher",					HasAuctionHouse=false},
	[68] = 	{id="Aydeewa Subterrane",				HasAuctionHouse=false},
	[69] = 	{id="Leujaoam Sanctum",					HasAuctionHouse=false},
	[70] = 	{id="Chocobo Circuit",					HasAuctionHouse=false},
	[71] = 	{id="The Colosseum",					HasAuctionHouse=false},
	[72] = 	{id="Alzadaal Undersea Ruins",			HasAuctionHouse=false},
	[73] = 	{id="Zhayolm Remnants",					HasAuctionHouse=false},
	[74] = 	{id="Arrapago Remnants",				HasAuctionHouse=false},
	[75] = 	{id="Bhaflau Remnants",					HasAuctionHouse=false},
	[76] = 	{id="Silver Sea Remnants",				HasAuctionHouse=false},
	[77] = 	{id="Nyzul Isle",						HasAuctionHouse=false},
	[78] = 	{id="Hazhalm Testing Grounds",			HasAuctionHouse=false},
	[79] = 	{id="Caedarva Mire",					HasAuctionHouse=false},
	[80] = 	{id="Southern San d'Oria [S]",			HasAuctionHouse=false},
	[81] = 	{id="East Ronfaure [S]",				HasAuctionHouse=false},
	[82] = 	{id="Jugner Forest [S]",				HasAuctionHouse=false},
	[83] = 	{id="Vunkerl Inlet [S]",				HasAuctionHouse=false},
	[84] = 	{id="Batallia Downs [S]",				HasAuctionHouse=false},
	[85] = 	{id="La Vaule [S]",						HasAuctionHouse=false},
	[86] = 	{id="Everbloom Hollow",					HasAuctionHouse=false},
	[87] = 	{id="Bastok Markets [S]",				HasAuctionHouse=false},
	[88] = 	{id="North Gustaberg [S]",				HasAuctionHouse=false},
	[89] = 	{id="Grauberg [S]",						HasAuctionHouse=false},
	[90] = 	{id="Pashhow Marshlands [S]",			HasAuctionHouse=false},
	[91] = 	{id="Rolanberry Fields [S]",			HasAuctionHouse=false},
	[92] = 	{id="Beadeaux [S]",						HasAuctionHouse=false},
	[93] = 	{id="Ruhotz Silvermines",				HasAuctionHouse=false},
	[94] = 	{id="Windurst Waters [S]",				HasAuctionHouse=false},
	[95] = 	{id="West Sarutabaruta [S]",			HasAuctionHouse=false},
	[96] = 	{id="Fort Karugo-Narugo [S]",			HasAuctionHouse=false},
	[97] = 	{id="Meriphataud Mountains [S]",		HasAuctionHouse=false},
	[98] = 	{id="Sauromugue Champaign [S]",			HasAuctionHouse=false},
	[99] = 	{id="Castle Oztroja [S]",				HasAuctionHouse=false},
	[100] = {id="West Ronfaure",					HasAuctionHouse=false},
	[101] = {id="East Ronfaure",					HasAuctionHouse=false},
	[102] = {id="La Theine Plateau",				HasAuctionHouse=false},
	[103] = {id="Valkurm Dunes",					HasAuctionHouse=false},
	[104] = {id="Jugner Forest",					HasAuctionHouse=false},
	[105] = {id="Batallia Downs",					HasAuctionHouse=false},
	[106] = {id="North Gustaberg",					HasAuctionHouse=false},
	[107] = {id="South Gustaberg",					HasAuctionHouse=false},
	[108] = {id="Konschtat Highlands",				HasAuctionHouse=false},
	[109] = {id="Pashhow Marshlands",				HasAuctionHouse=false},
	[110] = {id="Rolanberry Fields",				HasAuctionHouse=false},
	[111] = {id="Beaucedine Glacier",				HasAuctionHouse=false},
	[112] = {id="Xarcabard",						HasAuctionHouse=false},
	[113] = {id="Cape Teriggan",					HasAuctionHouse=false},
	[114] = {id="Eastern Altepa Desert",			HasAuctionHouse=false},
	[115] = {id="West Sarutabaruta",				HasAuctionHouse=false},
	[116] = {id="East Sarutabaruta",				HasAuctionHouse=false},
	[117] = {id="Tahrongi Canyon",					HasAuctionHouse=false},
	[118] = {id="Buburimu Peninsula",				HasAuctionHouse=false},
	[119] = {id="Meriphataud Mountains",			HasAuctionHouse=false},
	[120] = {id="Sauromugue Champaign",				HasAuctionHouse=false},
	[121] = {id="The Sanctuary of Zi'Tah",			HasAuctionHouse=false},
	[122] = {id="Ro'Maeve",							HasAuctionHouse=false},
	[123] = {id="Yuhtunga Jungle",					HasAuctionHouse=false},
	[124] = {id="Yhoator Jungle",					HasAuctionHouse=false},
	[125] = {id="Western Altepa Desert",			HasAuctionHouse=false},
	[126] = {id="Qufim Island",						HasAuctionHouse=false},
	[127] = {id="Behemoth's Dominion",				HasAuctionHouse=false},
	[128] = {id="Valley of Sorrows",				HasAuctionHouse=false},
	[129] = {id="Ghoyu's Reverie",					HasAuctionHouse=false},
	[130] = {id="Ru'Aun Gardens",					HasAuctionHouse=false},
	[131] = {id="Mordion Gaol",						HasAuctionHouse=false},
	[132] = {id="Abyssea - La Theine",				HasAuctionHouse=false},
	[133] = {id="Outer Ra'Kaznar [U2]",				HasAuctionHouse=false},
	[134] = {id="Dynamis - Beaucedine",				HasAuctionHouse=false},
	[135] = {id="Dynamis - Xarcabard",				HasAuctionHouse=false},
	[136] = {id="Beaucedine Glacier [S]",			HasAuctionHouse=false},
	[137] = {id="Xarcabard [S]",					HasAuctionHouse=false},
	[138] = {id="Castle Zvahl Baileys [S]",			HasAuctionHouse=false},
	[139] = {id="Horlais Peak",						HasAuctionHouse=false},
	[140] = {id="Ghelsba Outpost",					HasAuctionHouse=false},
	[141] = {id="Fort Ghelsba",						HasAuctionHouse=false},
	[142] = {id="Yughott Grotto",					HasAuctionHouse=false},
	[143] = {id="Palborough Mines",					HasAuctionHouse=false},
	[144] = {id="Waughroon Shrine",					HasAuctionHouse=false},
	[145] = {id="Giddeus",							HasAuctionHouse=false},
	[146] = {id="Balga's Dais",						HasAuctionHouse=false},
	[147] = {id="Beadeaux",							HasAuctionHouse=false},
	[148] = {id="Qulun Dome",						HasAuctionHouse=false},
	[149] = {id="Davoi",							HasAuctionHouse=false},
	[150] = {id="Monastic Cavern",					HasAuctionHouse=false},
	[151] = {id="Castle Oztroja",					HasAuctionHouse=false},
	[152] = {id="Altar Room",						HasAuctionHouse=false},
	[153] = {id="The Boyahda Tree",					HasAuctionHouse=false},
	[154] = {id="Dragon's Aery",					HasAuctionHouse=false},
	[155] = {id="Castle Zvahl Keep [S]",			HasAuctionHouse=false},
	[156] = {id="Throne Room [S]",					HasAuctionHouse=false},
	[157] = {id="Middle Delkfutt's Tower",			HasAuctionHouse=false},
	[158] = {id="Upper Delkfutt's Tower",			HasAuctionHouse=false},
	[159] = {id="Temple of Uggalepih",				HasAuctionHouse=false},
	[160] = {id="Den of Rancor",					HasAuctionHouse=false},
	[161] = {id="Castle Zvahl Baileys",				HasAuctionHouse=false},
	[162] = {id="Castle Zvahl Keep",				HasAuctionHouse=false},
	[163] = {id="Sacrificial Chamber",				HasAuctionHouse=false},
	[164] = {id="Garlaige Citadel [S]",				HasAuctionHouse=false},
	[165] = {id="Throne Room",						HasAuctionHouse=false},
	[166] = {id="Ranguemont Pass",					HasAuctionHouse=false},
	[167] = {id="Bostaunieux Oubliette",			HasAuctionHouse=false},
	[168] = {id="Chamber of Oracles",				HasAuctionHouse=false},
	[169] = {id="Toraimarai Canal",					HasAuctionHouse=false},
	[170] = {id="Full Moon Fountain",				HasAuctionHouse=false},
	[171] = {id="Crawlers' Nest [S]",				HasAuctionHouse=false},
	[172] = {id="Zeruhn Mines",						HasAuctionHouse=false},
	[173] = {id="Korroloka Tunnel",					HasAuctionHouse=false},
	[174] = {id="Kuftal Tunnel",					HasAuctionHouse=false},
	[175] = {id="The Eldieme Necropolis [S]",		HasAuctionHouse=false},
	[176] = {id="Sea Serpent Grotto",				HasAuctionHouse=false},
	[177] = {id="Ve'Lugannon Palace",				HasAuctionHouse=false},
	[178] = {id="The Shrine of Ru'Avitau",			HasAuctionHouse=false},
	[179] = {id="Stellar Fulcrum",					HasAuctionHouse=false},
	[180] = {id="La'Loff Amphitheater",				HasAuctionHouse=false},
	[181] = {id="The Celestial Nexus",				HasAuctionHouse=false},
	[182] = {id="Walk of Echoes",					HasAuctionHouse=false},
	[183] = {id="Maquette Abdhaljs-LegionA",		HasAuctionHouse=false},
	[184] = {id="Lower Delkfutt's Tower",			HasAuctionHouse=false},
	[185] = {id="Dynamis - San d'Oria",				HasAuctionHouse=false},
	[186] = {id="Dynamis - Bastok",					HasAuctionHouse=false},
	[187] = {id="Dynamis - Windurst",				HasAuctionHouse=false},
	[188] = {id="Dynamis - Jeuno",					HasAuctionHouse=false},
	[189] = {id="Outer Ra'Kaznar [U3]",				HasAuctionHouse=false},
	[190] = {id="King Ranperre's Tomb",				HasAuctionHouse=false},
	[191] = {id="Dangruf Wadi",						HasAuctionHouse=false},
	[192] = {id="Inner Horutoto Ruins",				HasAuctionHouse=false},
	[193] = {id="Ordelle's Caves",					HasAuctionHouse=false},
	[194] = {id="Outer Horutoto Ruins",				HasAuctionHouse=false},
	[195] = {id="The Eldieme Necropolis",			HasAuctionHouse=false},
	[196] = {id="Gusgen Mines",						HasAuctionHouse=false},
	[197] = {id="Crawlers' Nest",					HasAuctionHouse=false},
	[198] = {id="Maze of Shakhrami",				HasAuctionHouse=false},
	[200] = {id="Garlaige Citadel",					HasAuctionHouse=false},
	[201] = {id="Cloister of Gales",				HasAuctionHouse=false},
	[202] = {id="Cloister of Storms",				HasAuctionHouse=false},
	[203] = {id="Cloister of Frost",				HasAuctionHouse=false},
	[204] = {id="Fei'Yin",							HasAuctionHouse=false},
	[205] = {id="Ifrit's Cauldron",					HasAuctionHouse=false},
	[206] = {id="Qu'Bia Arena",						HasAuctionHouse=false},
	[207] = {id="Cloister of Flames",				HasAuctionHouse=false},
	[208] = {id="Quicksand Caves",					HasAuctionHouse=false},
	[209] = {id="Cloister of Tremors",				HasAuctionHouse=false},
	[211] = {id="Cloister of Tides",				HasAuctionHouse=false},
	[212] = {id="Gustav Tunnel",					HasAuctionHouse=false},
	[213] = {id="Labyrinth of Onzozo",				HasAuctionHouse=false},
	[215] = {id="Abyssea - Attohwa",				HasAuctionHouse=false},
	[216] = {id="Abyssea - Misareaux",				HasAuctionHouse=false},
	[217] = {id="Abyssea - Vunkerl",				HasAuctionHouse=false},
	[218] = {id="Abyssea - Altepa",					HasAuctionHouse=false},
	[220] = {id="Ship bound for Selbina",			HasAuctionHouse=false},
	[221] = {id="Ship bound for Mhaura",			HasAuctionHouse=false},
	[222] = {id="Provenance",						HasAuctionHouse=false},
	[223] = {id="San d'Oria-Jeuno Airship",			HasAuctionHouse=false},
	[224] = {id="Bastok-Jeuno Airship",				HasAuctionHouse=false},
	[225] = {id="Windurst-Jeuno Airship",			HasAuctionHouse=false},
	[226] = {id="Kazham-Jeuno Airship",				HasAuctionHouse=false},
	[227] = {id="Ship bound for Selbina",			HasAuctionHouse=false},
	[228] = {id="Ship bound for Mhaura",			HasAuctionHouse=false},
	[229] = {id="Throne Room [V]",					HasAuctionHouse=false},
	[230] = {id="Southern San d'Oria",				HasAuctionHouse=true},
	[231] = {id="Northern San d'Oria",				HasAuctionHouse=false},
	[232] = {id="Port San d'Oria",					HasAuctionHouse=true},
	[233] = {id="Chateau d'Oraguille",				HasAuctionHouse=false},
	[234] = {id="Bastok Mines",						HasAuctionHouse=true},
	[235] = {id="Bastok Markets",					HasAuctionHouse=true},
	[236] = {id="Port Bastok",						HasAuctionHouse=false},
	[237] = {id="Metalworks",						HasAuctionHouse=false},
	[238] = {id="Windurst Waters",					HasAuctionHouse=false},
	[239] = {id="Windurst Walls",					HasAuctionHouse=true},
	[240] = {id="Port Windurst",					HasAuctionHouse=false},
	[241] = {id="Windurst Woods",					HasAuctionHouse=true},
	[242] = {id="Heavens Tower",					HasAuctionHouse=false},
	[243] = {id="Ru'Lude Gardens",					HasAuctionHouse=true},
	[244] = {id="Upper Jeuno",						HasAuctionHouse=true},
	[245] = {id="Lower Jeuno",						HasAuctionHouse=true},
	[246] = {id="Port Jeuno",						HasAuctionHouse=true},
	[247] = {id="Rabao",							HasAuctionHouse=true},
	[248] = {id="Selbina",							HasAuctionHouse=false},
	[249] = {id="Mhaura",							HasAuctionHouse=false},
	[250] = {id="Kazham",							HasAuctionHouse=true},
	[251] = {id="Hall of the Gods",					HasAuctionHouse=false},
	[252] = {id="Norg",								HasAuctionHouse=true},
	[253] = {id="Abyssea - Uleguerand",				HasAuctionHouse=false},
	[254] = {id="Abyssea - Grauberg",				HasAuctionHouse=false},
	[255] = {id="Abyssea - Empyreal Paradox",		HasAuctionHouse=false},
	[256] = {id="Western Adoulin",					HasAuctionHouse=true},
	[257] = {id="Eastern Adoulin",					HasAuctionHouse=true},
	[258] = {id="Rala Waterways",					HasAuctionHouse=false},
	[259] = {id="Rala Waterways [U]",				HasAuctionHouse=false},
	[260] = {id="Yahse Hunting Grounds",			HasAuctionHouse=false},
	[261] = {id="Ceizak Battlegrounds",				HasAuctionHouse=false},
	[262] = {id="Foret de Hennetiel",				HasAuctionHouse=false},
	[263] = {id="Yorcia Weald",						HasAuctionHouse=false},
	[264] = {id="Yorcia Weald [U]",					HasAuctionHouse=false},
	[265] = {id="Morimar Basalt Fields",			HasAuctionHouse=false},
	[266] = {id="Marjami Ravine",					HasAuctionHouse=false},
	[267] = {id="Kamihr Drifts",					HasAuctionHouse=false},
	[268] = {id="Sih Gates",						HasAuctionHouse=false},
	[269] = {id="Moh Gates",						HasAuctionHouse=false},
	[270] = {id="Cirdas Caverns",					HasAuctionHouse=false},
	[271] = {id="Cirdas Caverns [U]",				HasAuctionHouse=false},
	[272] = {id="Dho Gates",						HasAuctionHouse=false},
	[273] = {id="Woh Gates",						HasAuctionHouse=false},
	[274] = {id="Outer Ra'Kaznar",					HasAuctionHouse=false},
	[275] = {id="Outer Ra'Kaznar [U1]",				HasAuctionHouse=false},
	[276] = {id="Ra'Kaznar Inner Court",			HasAuctionHouse=false},
	[277] = {id="Ra'Kaznar Turris",					HasAuctionHouse=false},
	[278] = {id="Gwora - Corridor",					HasAuctionHouse=false},
	[279] = {id="Walk of Echoes [P2]",				HasAuctionHouse=false},
	[280] = {id="Mog Garden",						HasAuctionHouse=false},
	[281] = {id="Leafallia",						HasAuctionHouse=false},
	[282] = {id="Mount Kamihr",						HasAuctionHouse=false},
	[283] = {id="Silver Knife",						HasAuctionHouse=false},
	[284] = {id="Celennia Memorial Library",		HasAuctionHouse=false},
	[285] = {id="Feretory",							HasAuctionHouse=false},
	[287] = {id="Maquette Abdhaljs-LegionB",		HasAuctionHouse=false},
	[288] = {id="Escha - Zi'Tah",					HasAuctionHouse=false},
	[289] = {id="Escha - Ru'Aun",					HasAuctionHouse=false},
	[290] = {id="Desuetia - Empyreal Paradox",		HasAuctionHouse=false},
	[291] = {id="Reisenjima",						HasAuctionHouse=false},
	[292] = {id="Reisenjima Henge",					HasAuctionHouse=false},
	[293] = {id="Reisenjima Sanctorium",			HasAuctionHouse=false},
	[294] = {id="Dynamis - San d'Oria [D]",			HasAuctionHouse=false},
	[295] = {id="Dynamis - Bastok [D]",				HasAuctionHouse=false},
	[296] = {id="Dynamis - Windurst [D]",			HasAuctionHouse=false},
	[297] = {id="Dynamis - Jeuno [D]",				HasAuctionHouse=false},
	[298] = {id="Walk of Echoes [P1]",				HasAuctionHouse=false},
	[299] = {id="Gwora - Throne Room",				HasAuctionHouse=false}
}